### PR TITLE
Update urls.py

### PR DESCRIPTION
**Pull request by spideralessio**
patterns has been removed in Dango 1.10

### CODE REVIEW

**Comment by nguyentrantuan** [comment]
can we accept this to make the newer Django version works?

**Comment by pisapapiros** [comment]
It still throws an error regarding the urls:

```
 ...\lib\site-packages\paypal\express\urls.py", line 7, in <module>
    urlpatterns = patterns('',
NameError: name 'patterns' is not defined
```

I'm using Django=1.10.7, django-oscar=1.4 and django-oscar-paypal=0.9.7. 

How are you using it?

**Comment by spideralessio** [comment]
I'm not using it

**Comment by pisapapiros** [comment]
so, are you using a different module to accept PayPal payments on your Oscar site? 
Appreciate any help, thanks :)

**Comment by spideralessio** [comment]
When I saw django oscar was not supported as I wanted i decided to not use
django oscar

**Comment by solarissmoke** [comment]
I've addressed this and other issues in  #159.

**Pull request closed without merging**
