### PR TITLE
:sunny: Remove from future html template tags for 1.9 compatibility.

### PR DESCRIPTION
**Pull request by SalahAdDin**
With last django version we have to remove from future tags.
In addition, with last `django-oscar` version we don't need use `append` function, and `shop` was removed from `oscar.apps`. So, in the documentation we change the paypal urls importing way for once more adequate.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Added some change for `django 1.10` incompatibilities with urls.

**Comment by SalahAdDin** [comment]
Guys!!!

**Comment by glibersat** [comment]
Hi guys,
When do you plan to merge that? It's an important fix, most of projects are now using django 1.9+.
Thank you!

**Comment by SalahAdDin** [comment]
@sasha0 Man, please.

**Comment by SalahAdDin** [comment]
@sasha0 Man, please.
@glibersat Use my fork if you want.

**Comment by solarissmoke** [comment]
I've addressed this and other issues in #159.

**Pull request closed without merging**
