### PR TITLE
using six from pypi package for django3 compatibility

### PR DESCRIPTION
**Pull request by snake-soft**
https://github.com/django-oscar/django-oscar-paypal/issues/255

### CODE REVIEW

**Review by solarissmoke — CHANGES_REQUESTED** [review]
We've dropped support for Python 2 - so I think it's better instead to drop all use of Python 2 compatible shims instead of using `six`.

**Comment by sasha0** [comment]
I agree.

**Comment by sasha0** [comment]
Alright, I already addressed that.

**Comment by solarissmoke** [comment]
Closing on the basis that Python 2 support will be dropped entirely in the next release.

**Pull request closed without merging**
